### ISSUE TITLE
Steal some methods from vknet/vk + https://vkdotnet.codeplex.com/

### ISSUE THREAD

**Issue by kasthack** [EpicMorg/kasthack.vksharp#5]
https://github.com/vknet/vk
- [X] audio.editalbum
- [X] audio.getpopular
- [X] audio.getrecommendations
- [X] audio.movetoalbum
- [X] audio.setbroadcast
- [X] fave.getlinks
- [X] fave.getphotos
- [x] fave.getposts
- [X] fave.getusers
- [X] fave.getvideos
- [X] friends.addlist
- [X] friends.arefriends
- [X] friends.edit
- [X] friends.editlist
- [X] friends.getlists
- [X] friends.getonline
- [ ] groups.banuser
- [x] groups.get
- [ ] groups.getinvites
- [ ] groups.search
- [ ] messages.editchat
- [x] messages.get
- [ ] messages.getbyid
- [ ] messages.getchat
- [ ] messages.getchatusers
- [ ] messages.getdialogs
- [x] messages.gethistory
- [ ] messages.markasnew
- [ ] messages.search
- [ ] messages.searchdialogs
- [X] messages.send
- [x] users.getgroupsfull
- [x] users.getsubscription
- [ ] users.getuserbalance
- [ ] users.getusersettings
- [X] video.add
- [ ] video.addalbum
- [ ] video.createcomment
- [ ] video.edit
- [ ] video.editalbum
- [X] video.editcomment ??
- [ ] video.get
- [ ] video.getalbums
- [ ] video.getcomments
- [X] video.getnewtags
- [X] video.gettags
- [ ] video.getuservideos
- [ ] video.movetoalbum
- [X] video.puttag
- [x] video.restore
- [ ] video.save
- [ ] video.search
- [X] wall.getcomments ??

**Comment by KirillMB** [comment]
Было безумно круто если добавили бы groups.get прям в очень ближайшее время.
Этого метода очень не хватет.

**Comment by kasthack** [comment]
dead

**Comment by kasthack** [comment]
Wontfix
